# Generated by Django 5.2.7 on 2025-11-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('staff', 'Staff')], default='member', max_length=20),
        ),
    ]
