# Generated by Django 5.2.7 on 2025-11-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
