# Generated by Django 5.2.7 on 2026-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, only the user can see their activity'),
        ),
    ]
