# Generated by Django 5.2.7 on 2026-01-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_follower_likedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='jamendo_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
