# Generated by Django 5.2.7 on 2026-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_jamendo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, help_text='Artist image URL from Jamendo or other sources', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='jamendo_artist_id',
            field=models.CharField(blank=True, db_index=True, help_text='Jamendo artist ID for tracking', max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(condition=models.Q(('jamendo_artist_id__isnull', False)), fields=('jamendo_artist_id',), name='unique_jamendo_artist_id'),
        ),
    ]
